[package]
name = "js-framework-benchmark-yew"
version = "1.0.0"
authors = ["Isamu Mogi <isamu@leafytree.jp>"]

[dependencies]
rand = { version = "0", features = [ "stdweb" ] }
stdweb = "0"
yew = { git = "https://github.com/DenisKolodin/yew.git" }
